### ISSUE TITLE
Error Verifying Transaction

### ISSUE THREAD

**Issue by kahlflekzy** [devRaphael13/py4paystack#1]
Hello, I recently installed this package. It is an amazing software package. Well written (I went through the source) and well documented.
I ran into an error when attempting to run some functions. Below is what I did.
```
from django.conf import settings
from py4paystack.routes import transactions
import models
transaction = models.Transaction.objects.first()
key = settings.AUTHORIZATION_KEY
trans = transactions.Transaction(key)
response = trans.verify(transaction.tid)
```
With this I run into the error below.
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 889, in _get_hostport
    port = int(host[i+1:])
ValueError: invalid literal for int() with base 10: '//api.paystack.co'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\utilities\decorators.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\routes\transactions.py", line 110, in verify
    return self.get(path)
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\utilities\decorators.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\utilities\request.py", line 26, in get
    return self.request(path, 'GET', headers={'authorization': self.headers.pop('authorization')})
  File "C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\utilities\request.py", line 18, in request
    connection = http.client.HTTPSConnection('https://api.paystack.co')
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 1409, in __init__
    super(HTTPSConnection, self).__init__(host, port, timeout,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 851, in __init__
    (self.host, self.port) = self._get_hostport(host, port)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\http\client.py", line 894, in _get_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
http.client.InvalidURL: nonnumeric port: '//api.paystack.co'
```
While 
```
from py4paystack import Paystack
```
Yields
```
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
ImportError: cannot import name 'Paystack' from 'py4paystack' (C:\Users\User\PycharmProjects\project\venv\lib\site-packages\py4paystack\__init__.py)
```
Although this latter one isn't much of a problem I suppose, since I can get to the classes via `py4paystack.routes`.

Please can you clarify the cause of the first problem?

**Comment by devRaphael13** [comment]
Thank you very much for reaching out & for using my program, I'll update it
as soon as possible, just give me a day or 2. Have a nice day.

**Comment by devRaphael13** [comment]
The package has been updated, thank you.
